# Namespace
namespace: 3-tier

# MongoDB StatefulSet
mongodb:
  replicaCount: 1
  image:
    repository: mongo
    tag: 4.4.6
  containerPort: 27017
  command:
    - "/usr/bin/mongod"
    - "--wiredTigerCacheSizeGB"
    - "0.1"
    - "--bind_ip"
    - "0.0.0.0"
  storage:
    size: 1Gi
    accessModes:
      - ReadWriteOnce

# MongoDB Service
service:
  type: ClusterIP
  port: 27017
  targetport: 27017

#Backend deployment 
backend:
  replicaCount: 1
  image:
    repository: dhruvnotfound/3-tier-backend
    tag: 0.0.1
  containerPort: 3500
  liveness:
    path: /ok
    port: 3500
    initialDelaySeconds: 2
    periodSeconds: 5
  readiness:
    path: /ok
    port: 3500
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1

backendSVC:
  type: ClusterIP
  port: 80
  targetport: 3500

#Frontend deployment 
frontend:
  replicaCount: 1
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 25%
  image:
    repository: dhruvnotfound/3-tier-frontend
    tag: 0.0.1
  containerPort: 80

frontendSVC:
  port: 80
  type: ClusterIP
# PersistentVolume
persistentVolume:
  capacity: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

#Ingress
ingress:
  rules:
    - path: /frontend
      serviceName: frontend-service
      servicePort: 80
    - path: /backend
      serviceName: backend-service
      servicePort: 80
