apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: mongo-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}