apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    http:
      paths:
      {{- range $rules := .Values.ingress.rules }}
      - path: {{ $rules.path }}
        pathtype: prefix
        backend:
          service:
            name: {{ $rules.serviceName }}
            port:
              number: {{ $rules.servicePort }}
      {{- end}}